### PR TITLE
Adding spring-boot implementations of cloud native applications

### PR DESCRIPTION
**Pull request by wkorando**

### CODE REVIEW

**Comment by nheidloff** [comment]
Billy, this looks good. Unfortunately I'm having issues to build it. We had similar issues with the other Java services with different Java and Maven versions.

Could you also add a two stage build like here? https://github.com/IBM/cloud-native-starter/blob/master/scripts/deploy-articles-java-jee.sh#L28 and https://github.com/IBM/cloud-native-starter/blob/master/articles-java-jee/Dockerfile.nojava

**Comment by wkorando** [comment]
Added the two stage docker builds, also implemented the author service and have it use Open Liberty

**Comment by wkorando** [comment]
Adding a few more changes I missed

**Comment by wkorando** [comment]
Removed Spring Boot web-api

**Pull request closed without merging**
